spring:
  application:
    name: credentialservice
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5433/credential'
    username: postgres
    password: '123'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml
    liquibase-schema: public
    contexts: main
server:
  port: 8082
jwt:
  secret: "your-256-bit-secret-your-256-bit-secret"